### ISSUE TITLE
The [[DEFAULT]] firebase app has not been initialized!

### ISSUE THREAD

**Issue by lakshmannuli** [invertase/react-native-firebase#1795]
Here are my configurations

andriod/app/build.gradle

apply plugin: "com.android.application"

import com.android.build.OutputFile

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.sampleapp3"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    //compile project(':react-native-firebase')
      compile(project(':react-native-firebase')) {   
        transitive = false
    }
    compile project(':react-native-sqlite-storage')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules

        //Add these lines
    implementation "com.google.android.gms:play-services-base:15.0.0"
    implementation "com.google.firebase:firebase-core:15.0.2"
    implementation "com.google.firebase:firebase-messaging:15.0.2"

}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

android -> build.gradle

buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath 'com.google.gms:google-services:3.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}

package.json

{
  "name": "xxxxxxxx",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-firebase": "^5.1.1",
    "react-native-sqlite-storage": "^3.3.9"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by Chenjh1992** [comment]
missing [this](https://rnfirebase.io/docs/v5.x.x/messaging/android#Install-the-RNFirebase-Messaging-package)?

**Comment by Salakar** [comment]
Make sure you've added your google service json file to your project - this error is thrown if no firebase apps could be found - which the default one is auto-initialized via that json file.

**Comment by RecaMedia** [comment]
@lakshmannuli did you ever resolve this issue?

**Comment by shubham1164** [comment]
I am facing a similar issue after upgrading react-native to 0.59. anybody has solved it?

**Comment by ChibikeEchendu1** [comment]
i have the issue too

**Comment by sujitpk-perennial** [comment]
@shubham1164 @ChibikeEchendu1 
 - Are you able to resolve this ?

**Comment by shubham1164** [comment]
yes, just try to follow each and every step carefully in the docs. It will work for u too

**Comment by shubham1164** [comment]
I had created a new project at that time to make it work. try it

**Comment by sujitpk-perennial** [comment]
@shubham1164  Thanks. I will check again all the steps.

**Comment by Subway19** [comment]
@shubham1164 did it worked? Its not working for me after upgrading to 0.59.

**Comment by shubham1164** [comment]
Yes

**Comment by Subway19** [comment]
@shubham1164  can you help me out? I did followed all the steps above and all the steps from the documentation still nothing works

**Comment by Subway19** [comment]
`app.utils(...).checkPlayServicesAvailability is not a function`

I am getting this error now

**Comment by shubham1164** [comment]
Which platform u r using? Android(java or something else?), IOS, Web or so?

**Comment by Subway19** [comment]
Compiling on Android/Java

**Comment by shubham1164** [comment]
send me the not working code (app.utils(...).checkPlayServicesAvai ....) and RN version u r using

**Comment by Subway19** [comment]
This is my react-native-info

```

info 
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz
      Memory: 131.39 MB / 7.69 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.3.0 - ~/.nvm/versions/node/v8.3.0/bin/node
      npm: 5.3.0 - ~/.nvm/versions/node/v8.3.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 24.0.1, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64
    npmPackages:
      react: ^16.8.3 => 16.8.6 
      react-native: ^0.59.10 => 0.59.10 

```

And the error screen

![Screenshot_2019-07-19-12-20-03-324_com orowealth orowealthv11](https://user-images.githubusercontent.com/14835320/61515328-fd2fff00-aa1f-11e9-8e4b-d58c9e4cd07e.png)

**Comment by shubham1164** [comment]
Make sure that u have followed the guide properly and updated the build.gradle as per the documentation of the RNFirebase

**Comment by shubham1164** [comment]
search for checkPlayServicesAvailability in the entire source code

**Comment by shubham1164** [comment]
Then try to create a new project with just including the RNfirebase and then try

**Comment by Subway19** [comment]
Created a new issue here #2380 . If anybody can help

**Comment by arivanandan** [comment]
Using `classpath 'com.google.gms:google-services:4.0.0'` made it work for me. Probably clashing with deps from other modules. 4.1.0 gave me the error in title and 4.2.0 wouldn't work because of some other deps `net.minidev:json-smart`.

**Comment by Subway19** [comment]
@arivanandan  Did you get this error - `app.utils(...).checkPlayServicesAvailability` is not a function ?

**Comment by RemmyBisimbeko** [comment]
Add apply plugin: 'com.google.gms.google-services' in android/app/build.gradle on line 2 and at the bottom
Then 
```
dependencies {
++ classpath 'com.google.gms:google-services:4.2.0'
}
``` in android/build.gradle
