### ISSUE TITLE
Build Failed on RN 0.47

### ISSUE THREAD

**Issue by fungilation** [invertase/react-native-firebase#301]
### Environment

1. Target Platform (e.g. iOS, Android): iOS
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra 10.12.6
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Xcode, iOS 10.3
4. React Native version (e.g. 0.45.1): 0.47.1
5. RNFirebase Version (e.g. 2.0.2): 2.0.5

Running `react-native run-ios` turn up a bunch of warnings while building the various RNFirebase native modules, ending with this:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNFirebaseDatabaseReference", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseDatabase.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)



** BUILD FAILED **
```

**Comment by hofuchi** [comment]
Similar to #300 , seems to happen when upgrading react-native to `^0.47.0`. Downgrading should fix the issue meanwhile

**Comment by j-fro** [comment]
I'm getting this same error after upgrading to 0.47.0, but the error persists even after nuking my project folder and installing from a fresh clone on 0.46.0

**Comment by fungilation** [comment]
Interestingly, after downgrading RN back to 0.46, same build error above still happens. But my app launch and run fine.

**Comment by Ehesp** [comment]
On Android at least, some funky caching happens in the `build` directories which sometimes need nuking, need to double check iOS.

**Comment by evgeni-tsn** [comment]
Same issue here. Rollback to _0.46.4_ builds successfully.

**Comment by Ehesp** [comment]
Does anyone have anymore friendly logs? Seems to be quite a raw output.

**Comment by fungilation** [comment]
What kind of logs, more from `react-native run-ios`? Do you not reproduce a build failure on RN 0.47?

**Comment by Ehesp** [comment]
Xcode should hopefully show the full logs if you can get it working, usually more user friendly. Not had a chance to try on 0.47 yet, will be giving it a test tomorrow morning.

**Comment by evgeni-tsn** [comment]
We got success build with the Pull Request [#299](https://github.com/invertase/react-native-firebase/issues/299) 
Reference: [#300](https://github.com/invertase/react-native-firebase/issues/300)

**Comment by fungilation** [comment]
I've been pulling my hair out tonight. I'm hitting this in Xcode, *after* downgrading RN back to 0.46.4. Nothing works, including nuking ios/build and ~/Library/Developer/Xcode/DerivedData/*. Tried reinstalling/relinking `react-native-firebase`.

Xcode fail log:
```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_RNFirebaseDatabaseReference", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseDatabase.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by chrisbianca** [comment]
Have you re-run `pod install`?

**Comment by fungilation** [comment]
I should also note that I ran `pod update` a few days ago. Not sure if updated pods is the real issue, not with RN? This is my `pod install` output:

```
Downloading dependencies
Using Firebase (4.0.4)
Using FirebaseAnalytics (4.0.2)
Using FirebaseAuth (4.0.0)
Using FirebaseCore (4.0.4)
Using FirebaseDatabase (4.0.0)
Using FirebaseInstanceID (2.0.0)
Using FirebaseMessaging (2.0.0)
Using FirebasePerformance (1.0.3)
Using FirebaseRemoteConfig (2.0.1)
Using FirebaseStorage (2.0.0)
Using GTMSessionFetcher (1.1.11)
Using GoogleToolboxForMac (2.1.1)
Using Protobuf (3.3.0)
Using RNFirebase (2.0.5)
Using React (0.47.1)
Using Yoga (0.47.1.React)
Using nanopb (0.3.8)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 11 dependencies from the Podfile and 17 total pods installed.
```

**Comment by fungilation** [comment]
I just tried starting somewhat clean with a new `git clone`ed directory of my project, which doesn't include `node_modules/`. I ran `yarn` and `pod install`. Xcode eventually still hit the same build failing error.

I upgraded RN to 0.47.1 again. Xcode build also fail on same error.

**Comment by chrisbianca** [comment]
Hey guys, I have just released v2.1.0 which supported RN 0.47 as well as earlier versions.  Thanks for reporting the issue.

**Comment by chaitanya0bhagvan** [comment]
@chrisbianca Looks like this error is not related to react-native. This is happening in react-native-firebase v2.0.5 and above. This is not happening in 2.0.4

**Comment by chrisbianca** [comment]
`RNFirebaseDatabaseReference` was introduced in v2.0.5.

To ensure that it is picked up in your build, you will need to run `pod install` to make sure that new files from RNFirebase are included in the Cocoapod build.

I assume that you are linking RNFirebase using Cocoapods and not manually?

**Comment by chaitanya0bhagvan** [comment]
@chrisbianca I was not using RNFirebase Cocoapods. To start using Cocoapods do I have to move react-native also ?

**Comment by chrisbianca** [comment]
@chaitanya0bhagvan Interesting, I'll look at why it might not work when linking manually. Presumably the file hasn't been added to the project properly.

To use cocoapods, you don't have to move react-native, but you do need to make reference to it from within your pod file, so that RNFirebase knows where to find it.

**Comment by chrisbianca** [comment]
@chaitanya0bhagvan I've just pushed a change to hopefully fix things for you so you don't need to set up Cocoapods.

Can you try installing the latest commit from master by doing:

`npm install --save git+https://github.com/invertase/react-native-firebase.git`

Then try running the project again?

**Comment by thevishnupradeep** [comment]
I am facing a similar issue. Its not fixed in the latest commit either. @chrisbianca 

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNFirebaseDatabaseReference", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseDatabase.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by chrisbianca** [comment]
@thevishnupradeep have you linked RNFirebase manually or using Cocoapods?

**Comment by thevishnupradeep** [comment]
I first tried with cocoa pods first and then with react-native link. Both produced the same result

**Comment by chrisbianca** [comment]
Xcode is notorious for build issues.
Try doing a product > clean, then restarting Xcode and trying the build again

**Comment by thevishnupradeep** [comment]
It works!
These are the things I did:

1. Close xcode & Delete the [derived data](https://stackoverflow.com/questions/38016143/how-to-delete-derived-data-in-xcode-8)
2. Delete pods folder, .xcworkspace and podfile.lock files.
3. Install RNFirebase through the above command

This should help you compile the file.

**Comment by chaitanya0bhagvan** [comment]
@chrisbianca I tried to use Cocoapods and ended with many weird errors. I reverted to my original setup and used the react-native-firebase from the master and it is working without any issue. Thank you for the very quick response, will wait for the new version on npm.

**Comment by fungilation** [comment]
Ok, I've fixed it. Builds fine on RN 0.47.1.

What I did that I think contributed to the fix:

1. yarn upgraded react-native-firebase to 2.1.0
2. UNDO `react-native link` I did and forgot that react-native-firebase shouldn't use it. Apparently can't! Not sure if this was the only reason my build failed, but having tried everything, even after upgrading react-native-firebase to 2.1.0 or to git master to no avail, this was what ultimately resolved the build fail in Xcode.

Note that I also did a bunch of other cache busting measures, like nuking ~/Library/Developer/Xcode/DerivedData/*, node_modules/, ios/build/, iod/Pods/, ios/Podfile.lock

Thanks for the quick release in 2.1.0.

**Comment by jacksontbryan** [comment]
This has been a pretty frustrating day.  Getting the same error but not in relation to upgrading to RN 0.47.1.  I am still on 0.46.4.

RNFirebaseDatabaseReference appears to have been added recently.   My build was failing finding a reference to this class.  Build worked in xcode but not from react-native run-ios.  I tried everything mentioned on this thread as far as clearing caches and reinstalling npm/pds.  A solution that worked on my machine was pod install seemed to work.  

On a coworkers machine, I am unable to get a build to work using react-native run-ios at all.  Builds work in xcode.  It appears his build is getting an old copy of RN Firebase but I have no idea where.

Is react-native run-ios problematic when used in conjunction with cocopods?

**Comment by chaitanya0bhagvan** [comment]
@jacksontbryan Xcode sucks at cleaning and there always seem to be some remnant of the build lingering somewhere. 
When I want to clean a Xcode project I do the following

```
$ cd <ios-project-dir>
$ rm -rf  ~/Library/Developer/Xcode/DerivedData/ Pods/ Podfile.lock build/
$ pod install
```

Note: Your build and DerivedData paths might differ from mine.
