### ISSUE TITLE
'RCTDevMenu.h' file not found Compilation Error

### ISSUE THREAD

**Issue by MathiasGilson** [invertase/react-native-firebase#390]
Cannot compile with RN v0.48.1 using CocoaPods
react-native-firebase v2.1.4

**Comment by MathiasGilson** [comment]
I fixed it by explicitly importing DevSupport with the React pod
here is my Podfile
```
# Required by RNFirebase
pod 'Firebase/Core'
pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

# [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
pod 'Firebase/Auth'

pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'BatchedBridge',
  'Core',
  'DevSupport' # <= ADD THIS LINE
]
```

**Comment by JackThomson2** [comment]
Just hit this issue also. I tried removing the import and the line referencing it but the app crashes on load

**Comment by MathiasGilson** [comment]
check my solution and tell me if it worked for you 😉
(I had already solved it so I closed the issue right after opening it)

**Comment by JackThomson2** [comment]
Haha just saw it and it built! Thanks for the help
