### ISSUE TITLE
[🐛] Build fails on macOS M1 with sample React Native 0.71.1 project

### ISSUE THREAD

**Issue by iskeld** [invertase/react-native-firebase#6853]
## Issue

Hello, I created a sample React Native project using the [official tutorial](https://reactnative.dev/docs/environment-setup) (macOS + iOS - NON Expo version) and added React-Native-Firebase using the [official tutorial](https://rnfirebase.io).

_(I didn't add any code there besides the parts described in the Firebase tutorial - it's a plain sample React project and a plain Firebase setup)_

Unfortunately trying to run the app with `npx react-native run-ios` fails with the following errors:

```
Undefined symbols for architecture arm64:
  "facebook::jsi::Value::Value(facebook::jsi::Runtime&, facebook::jsi::Value const&)", referenced from:
      facebook::jsi::detail::toValue(facebook::jsi::Runtime&, facebook::jsi::Value const&) in Instance.o
  "facebook::jsi::Value::~Value()", referenced from:
      facebook::react::handleJSError(facebook::jsi::Runtime&, facebook::jsi::JSError const&, bool) in Instance.o
      facebook::jsi::Value facebook::jsi::Function::call<facebook::jsi::Value const&>(facebook::jsi::Runtime&, facebook::jsi::Value const&) const in Instance.o
      facebook::jsi::Function::call(facebook::jsi::Runtime&, facebook::jsi::Value const*, unsigned long) const in Instance.o
  "facebook::jsi::JSError::JSError(facebook::jsi::Runtime&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      facebook::react::handleJSError(facebook::jsi::Runtime&, facebook::jsi::JSError const&, bool) in Instance.o
  "facebook::jsi::JSError::~JSError()", referenced from:
      facebook::react::handleJSError(facebook::jsi::Runtime&, facebook::jsi::JSError const&, bool) in Instance.o
  "facebook::jsi::Object::getPropertyAsFunction(facebook::jsi::Runtime&, char const*) const", referenced from:
      facebook::react::handleJSError(facebook::jsi::Runtime&, facebook::jsi::JSError const&, bool) in Instance.o
  "facebook::jsi::Value::asObject(facebook::jsi::Runtime&) const &", referenced from:
      facebook::react::handleJSError(facebook::jsi::Runtime&, facebook::jsi::JSError const&, bool) in Instance.o
  "typeinfo for facebook::jsi::JSError", referenced from:
      facebook::react::handleJSError(facebook::jsi::Runtime&, facebook::jsi::JSError const&, bool) in Instance.o
      GCC_except_table884 in Instance.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

// (..... other stuff here)


** BUILD FAILED **


The following build commands failed:
	Ld /Users/maciek/Library/Developer/Xcode/DerivedData/FirebaseTest-fusgsehgailfihceoyuhtdzspptl/Build/Products/Debug-iphonesimulator/React-cxxreact/cxxreact.framework/cxxreact normal (in target 'React-cxxreact' from project 'Pods')
(1 failure)
```

Before adding Firebase the app runs fine.
It seems to work fine with React Native 0.69.7

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "FirebaseTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-firebase/app": "^16.5.1",
    "react": "18.2.0",
    "react-native": "0.71.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.7",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
$RNFirebaseAsStaticFramework = true
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'FirebaseTest' do
  use_frameworks!
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'FirebaseTestTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

```

#### `AppDelegate.mm`:

```objc
#import <Firebase.h>
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  self.moduleName = @"FirebaseTest";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

/// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
///
/// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
/// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
/// @return: `true` if the `concurrentRoot` feature is enabled. Otherwise, it returns `false`.
- (BOOL)concurrentRootEnabled
{
  return true;
}

@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 5.77 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/maciek/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /Users/maciek/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `16.5.1`
- **`Firebase` module(s) you're using that has the issue:**
  - I'm not using any modules 
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Not sure exactly what the differences are at the moment but have you seen + read the comments on + tried https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

The script starts from scratch (npx react-native init ...) and goes from there and last I checked a couple days ago was working fine

I pre-qualify the react-native releases during their release candidate phase and there was not much to handle in 0.71 that we did not already handle.

**Comment by gosunman** [comment]
# 🔥 follow below, it works!!
1. add GoogleService-Info.plist under /ios
2. change two files below (I added "for Firebase" comments to the code changed)

```bash
# <filename: ios/Podfile>
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RNFB' do
  config = use_native_modules!
  use_frameworks! :linkage => :static # for Firebase
  $RNFirebaseAsStaticFramework = true # for Firebase

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config, # for Firebase
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  $FirebaseSDKVersion = '10.4.0' # for Firebase
  target 'RNFBTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # for Firebase (all below)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["GCC_WARN_INHIBIT_ALL_WARNINGS"] = "YES"
      end
    end
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["CC"] = "clang"
        config.build_settings["LD"] = "clang"
        config.build_settings["CXX"] = "clang++"
        config.build_settings["LDPLUSPLUS"] = "clang++"
      end
    end
    
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
          config.build_settings['EXCLUDED_ARCHS'] = 'i386'
        end
      end
      aggregate_target.user_project.save
    end
    installer.pods_project.targets.each do |target|
      if (target.name.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ENABLE_BITCODE"] = "NO"
      end
    end
  end
end
```

```mm
// <filename: ios/[project name]/AppDelegate.mm>
#import "AppDelegate.h"
#import <Firebase.h> // for Firebase

#import <React/RCTBundleURLProvider.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) { [FIRApp configure]; } // for Firebase
  self.moduleName = @"RNFB";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

/// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
///
/// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
/// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
/// @return: `true` if the `concurrentRoot` feature is enabled. Otherwise, it returns `false`.
- (BOOL)concurrentRootEnabled
{
  return true;
}

@end
```

**Comment by gosunman** [comment]
@mikehardy 
I got the same problem today.
After looking your `make-demo.sh` script, I solved the problem.
There are some differences between your test code and the official instruction document.
I add `for Firebase` comments in [my comment](https://github.com/invertase/react-native-firebase/issues/6853#issuecomment-1400571275) to show the difference.
If possible, would you update the official document with it?
Thanks for all your work about react-native-firebase 👍

**Comment by mikehardy** [comment]
> There are some differences between your test code and the official instruction document.

Can you link to specific parts of the instructions where there are differences? I can correct them but I'm not sure where they are at the moment.

You can post deep links from github to the lines you mean (so we can make sure we are talking about the same thing) by browsing through the docs probably starting here: https://github.com/invertase/react-native-firebase/blob/main/docs/index.md

**Comment by gosunman** [comment]
@mikehardy 
I made a PR https://github.com/invertase/react-native-firebase/pull/6856
It might be easy to see the difference if you check the `files changes`

**Comment by oscar-gallog** [comment]
Do you know if this project ever worked? And I mean it for real. I have tried to use this library for years, and not a single time has it worked. I ended up using the firebase JS version. 
Even with the changes suggested by gosunman, it still returns the same errors. I mean, my project it's totally empty, but the moment I add this library, it just stops working.
Does anybody have any idea how to make this work? Or should I just drop this and stick to Firebase JS inside React Native?

<img width="429" alt="Screenshot 2023-01-23 at 10 40 39 PM" src="https://user-images.githubusercontent.com/51139459/214220192-d18ad50a-0b48-4a52-b923-138ea18e0232.png">

**Comment by gosunman** [comment]
@oscar-gallog 

Does it not work even if you copy and paste the codes I wrote above into your code?
I wonder if it didn't work even though you only pasted the codes I annotated as 'for Firebase' into your code.
You should not copy and paste the whole codes.
> recommend to use 'cmd + f' to highlight important codes needed to be changed
> with 'for Firebase' keyword in this page.

**Comment by iskeld** [comment]
@gosunman thank you very much! Your changes fixed the error.

**Comment by mikehardy** [comment]
> Do you know if this project ever worked?

In fact I have a fully scripted demonstration of it working, and it (the script) has been functional and working since - I forget exactly? - I think react-native 0.63 or so for x86-64 macs and M1 macs, and since I think 0.67 or so for macCatalyst builds even.

https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

Works every time.

**Comment by upngo** [comment]
The docs say that this plugin is not compatible with the New Architecture, which is part of 0.71.0 so doesn't that mean this plugin is currently not able to work with the latest version of RN?

> New Architecture: Fabric is not compatible with use_frameworks!. Community support to help fix use_frameworks support for New Architecture is welcome!
https://rnfirebase.io/#configure-firebase-with-ios-credentials

**Comment by jckw** [comment]
I believe the fix for me was changing: 

```
 use_frameworks!
```

to

```
use_frameworks! :linkage => :static
```

when using `$RNFirebaseAsStaticFramework = true`

**Comment by gosunman** [comment]
@jckw 
That is right!
So I made a PR (https://github.com/invertase/react-native-firebase/pull/6856/files)

**Comment by mikehardy** [comment]
@gosunman's PR had unfortunately "gone to sleep" (my fault! sorry) and should help others once I merge it - in process now
I'm going to close this as I *think* everyone is moving forward now and we've got a doc update for the future

**Comment by shubhamdeol** [comment]
turing `useFramework` on also required us to disable Flipper. 
Anyone know from where we can set the flags written in PodFile here?
I am talking about these lines. 
Do we need to define NO_FLIPPER in `.xcode.env` and set it as 1?

Or We will have to use react-native-config and have environment variables there?

This is bit out of context but bit related as we have to turn Flipper off when using useFramework

```
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
```

**Comment by Makhlab** [comment]
Is react-native-firebase/auth compatible with RN 0.71 at all? According to https://rnfirebase.io/, it seems incompatible with Fabric, which is used in RN v.0.71.

**Comment by mikehardy** [comment]
@Makhlab In a word: yes.

Repeatable proof: https://github.com/invertase/react-native-firebase/issues/6853#issuecomment-1401858418

Remember: Fabric / new architecture is optional and still in testing. Fabric is not compatible. Turn it off.

**Comment by caphun** [comment]
> > Do you know if this project ever worked?
> 
> In fact I have a fully scripted demonstration of it working, and it (the script) has been functional and working since - I forget exactly? - I think react-native 0.63 or so for x86-64 macs and M1 macs, and since I think 0.67 or so for macCatalyst builds even.
> 
> https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
> 
> Works every time.

I tried this script but it does not work. The build works but the app crashes on launch. 

Here's my environment:

Hardware Model: MacBookPro18,3
Process: rnfbdemo [20819]
Identifier: org.reactjs.native.example.rnfbdemo
Code Type: ARM-64 (Native)
Role: Foreground
Parent Process: launchd_sim [16416]
Coalition: com.apple.CoreSimulator.SimDevice.AC5F9E26-6C26-4AF8-9DAC-C8F2C1F01A6F [6488]
Responsible Process: SimulatorTrampoline [9070]
OS Version: macOS 13.4.1 (22F82)
Node version: 18.12.1
Ruby version: 3.2.2
react-native: 0.72.3
