### ISSUE TITLE
Cannot Find Module 'react-native-firebase'

### ISSUE THREAD

**Issue by jsm** [invertase/react-native-firebase#670]
### Issue

Hey I'm having trouble importing after upgrading to 3.1.1 and from looking at it, it doesn't seem to have an index.js file?

### Environment

1. Application Target Platform: Both

2. Development Operating System: High Sierra

3. Build Tools:

4. React Native version: 0.49.3

5. RNFirebase Version: 3.1.1

**Comment by Ehesp** [comment]
Have you tried nuking your node modules and installing?

**Comment by jsm** [comment]
@Ehesp Looking at the tag here: https://github.com/invertase/react-native-firebase/tree/v3.1.1 (also on latest master) there isn't an index.js file either. Unless I'm missing something

**Comment by jsm** [comment]
Looks like it was moved into the lib directory with this commit: https://github.com/invertase/react-native-firebase/commit/fbe73f5dcb09715d3bbc7e4e127ac508a9bd3efe

Is that valid and I'm just not importing it right somehow?

**Comment by jsm** [comment]
Nvm it was an issue with typescript: https://github.com/invertase/react-native-firebase/pull/671
