### ISSUE TITLE
 [v6] In-app-messaging Duplicate symbols after upgrading to 6.3.4 from 6.2.0

### ISSUE THREAD

**Issue by Magnai1030** [invertase/react-native-firebase#3319]
Sorry I got this error. Is it my fault or is it bug. I tried to remove all of my linking but it didn't work

> Version

React
    "react": "16.9.0",
    "react-native": "0.61.5",

Firebase
    "@react-native-firebase/app": "^6.3.4",
    "@react-native-firebase/auth": "^6.3.4",  
    "@react-native-firebase/iid": "^6.3.4",
    "@react-native-firebase/in-app-messaging": "^6.3.4",

> Error

`duplicate symbol '_OBJC_CLASS_$_FIRIAMDefaultDisplayImpl' in:
    /Users/pride/Library/Developer/Xcode/DerivedData/ToktokMobile-fkofwesguzkzlmeopbpkadfgrwjp/Build/Products/Debug-iphoneos/FirebaseInAppMessaging/libFirebaseInAppMessaging.a(FIRIAMDefaultDisplayImpl.o)
    /Users/pride/Library/Developer/Xcode/DerivedData/ToktokMobile-fkofwesguzkzlmeopbpkadfgrwjp/Build/Products/Debug-iphoneos/FirebaseInAppMessagingDisplay/libFirebaseInAppMessagingDisplay.a(FIRIAMDefaultDisplayImpl.o)
duplicate symbol '_OBJC_METACLASS_$_FIRIAMDefaultDisplayImpl' in:
    /Users/pride/Library/Developer/Xcode/DerivedData/ToktokMobile-fkofwesguzkzlmeopbpkadfgrwjp/Build/Products/Debug-iphoneos/FirebaseInAppMessaging/libFirebaseInAppMessaging.a(FIRIAMDefaultDisplayImpl.o)
    /Users/pride/Library/Developer/Xcode/DerivedData/ToktokMobile-fkofwesguzkzlmeopbpkadfgrwjp/Build/Products/Debug-iphoneos/FirebaseInAppMessagingDisplay/libFirebaseInAppMessagingDisplay.a(FIRIAMDefaultDisplayImpl.o)
ld: 2 duplicate symbols for architecture arm64 `

**Comment by mikehardy** [comment]
local project issue - it works in my demonstrator - https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh

I recommend https://github.com/pmadruga/react-native-clean-project/ to purge out all state then pod install and try again

**Comment by Magnai1030** [comment]
@mikehardy Okey thank you i am gonna try
