### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method getProjectId()Ljava/lang/String

### ISSUE THREAD

**Issue by ethanyuwang** [invertase/react-native-firebase#818]
### Issue

I have been trying to integrate this library with an ExpoKit project. I have followed the setup walkthrough and also https://github.com/EvanBacon/expo-native-firebase, but encountered this error:

![screenshot_1518028294](https://user-images.githubusercontent.com/17556945/35934642-f4eab032-0bf2-11e8-9936-4686270cc55a.png)

### Environment

Android

1. Application Target Platform:

OS: macOS High Sierra 10.13.1

2. Development Operating System:

 Android Studio: 2.3 AI-162.4069837

3. Build Tools:

4. React Native version:

react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

5. RNFirebase Version:

6. Firebase Module:

**Comment by chrisbianca** [comment]
@ethanyuwang Looking at your posts elsewhere, the issue is in your version of the google play services libraries. You're specifying 9.8.0 which I believe doesn't have this method available to it.  We're currently recommending at least 11.6.0 for the latest version of RNFirebase.

**Comment by ethanyuwang** [comment]
@chrisbianca 
Could anything else cause this error? Because according to this repo (https://github.com/EvanBacon/expo-native-firebase), He got it working with 9.8.0
