### ISSUE TITLE
App crash when using firebase.auth().signInWithCredential(credential)

### ISSUE THREAD

**Issue by AlexandreMaistret** [invertase/react-native-firebase#823]
**ISSUE**

Hello everyone,

I've just install this library, but the app crashs when launching `firebase.auth().signInWithCredential(credential);`

Here is my code : 

    let result = await LoginManager.logInWithReadPermissions(['public_profile', 'user_friends']);

    //Get access token
    let data = await AccessToken.getCurrentAccessToken();
    let accessToken = data.accessToken;

    const credential = await firebase.auth.FacebookAuthProvider.credential(accessToken);
    console.log(credential);

    //Create user in firebase
    await firebase.auth().signInWithCredential(credential);

    const DatabaseToken = await firebase.auth().currentUser.getIdToken();
    console.log(DatabaseToken);

The `console.log(credential)` is printed, but the `console.log(DatabaseToken)` isn't.

In the logs, I've got this error message : 

```
FATAL EXCEPTION: main
                                                            Process: com.MYAPPNAME PID: 13610
                                                            java.lang.NoSuchMethodError: No virtual method getMetadata()Lcom/google/firebase/auth/FirebaseUserMetadata; in class Lcom/google/firebase/auth/FirebaseUser; or its super classes (declaration of 'com.google.firebase.auth.FirebaseUser' appears in /data/app/com.MYAPPNAME-4/base.apk)
                                                                at io.invertase.firebase.auth.RNFirebaseAuth.firebaseUserToMap(RNFirebaseAuth.java:1551)
                                                                at io.invertase.firebase.auth.RNFirebaseAuth.access$000(RNFirebaseAuth.java:59)
                                                                at io.invertase.firebase.auth.RNFirebaseAuth$1.onAuthStateChanged(RNFirebaseAuth.java:98)
                                                                at com.google.firebase.auth.zzi.run(Unknown Source)
                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:167)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

These are my dependencies in android Studio : 

    dependencies {
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile project(':react-native-device-info')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-localization')
    compile project(':react-native-view-shot')
    compile project(':react-native-image-picker')
    compile project(':react-native-fs')
    compile project(':react-native-camera')
    compile project(':react-native-fbsdk')
    compile(project(':react-native-maps')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-base:11.4.2'
    compile "com.google.android.gms:play-services-auth:11.4.2"
    compile 'com.google.android.gms:play-services-gcm:11.4.2'
    compile 'com.google.android.gms:play-services-maps:11.4.2'
    compile 'com.google.android.gms:play-services-location:11.4.2'
    compile "com.google.firebase:firebase-core:11.4.2"
    compile "com.google.firebase:firebase-storage:11.4.2"
    compile "com.google.firebase:firebase-auth:11.4.2"
    compile project(':react-native-vector-icons')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-system-setting')
    compile project(':react-native-android-location-services-dialog-box')
    compile(project(':react-native-background-geolocation')) {
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:26.0.2"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'
    }

I've already tried to change all the versions of the `play-services dependencies` and `firebase dependencies`  to `11.6.0` and to `11.8.0`, it immediately crashs the app. 

**ENVIRONNEMENT**

react-native : 0.51.0
App create with `react-native init`
Android Studio : 3.0.1
Tested on real device WIKO

**Comment by chrisbianca** [comment]
@AlexandreMaistret `getMetadata` was added in a later version of the play services libraries than 11.4.2 so you will need to update to the latest version for this to work.

What is the crash log when updating to 11.8.0?

**Comment by AlexandreMaistret** [comment]
Hi @chrisbianca 

So I have set everything to 11.8.0 and this is the err message : 

    02-09 16:30:46.648 1883-2111/com.MYAPPNAME E/ReactNativeJS: Java exception in 'NativeModules'
                                                         
    java.lang.NoSuchMethodError: No static method 
    getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class 
    Lcom/google/android/gms/common/util/zzu; or its super classes (declaration of 
    'com.google.android.gms.common.util.zzu' appears in /data/app/com.MYAPPNAME-4/base.apk)

My dependencies :
 
    dependencies {
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile project(':react-native-device-info')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-localization')
    compile project(':react-native-view-shot')
    compile project(':react-native-image-picker')
    compile project(':react-native-fs')
    compile project(':react-native-camera')
    compile project(':react-native-fbsdk')
    compile(project(':react-native-maps')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-base:11.8.0'
    compile "com.google.android.gms:play-services-auth:11.8.0"
    compile 'com.google.android.gms:play-services-gcm:11.8.0'
    compile 'com.google.android.gms:play-services-maps:11.8.0'
    compile 'com.google.android.gms:play-services-location:11.8.0'
    compile "com.google.firebase:firebase-core:11.8.0"
    compile "com.google.firebase:firebase-storage:11.8.0"
    compile "com.google.firebase:firebase-auth:11.8.0"
    compile project(':react-native-vector-icons')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-system-setting')
    compile project(':react-native-android-location-services-dialog-box')
    compile(project(':react-native-background-geolocation')) {
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:26.1.0"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'
    }

I don't realy understand the err message. Also, Android Studio tell me this warning, which I don't really understand since  `com.google.android.gms:play-services-gcm:11.8.0` is specified in the dependencies to use 11.8.0: 

    All gms/firebase libraries must use the exact same version specification (mixing versions can lead to 
    runtime crashes). Found versions 11.8.0, 11.4.2. Examples include com.google.android.gms:play-
    services-auth:11.8.0 and com.google.android.gms:play-services-gcm:11.4.2

**Comment by chrisbianca** [comment]
One of your dependencies must be specifying the 11.4.2 version of gcm explicitly.

If you run: `./gradlew app:dependencies` from with the android directory of your project, it will give you a graph of all the interdependencies.  Check which is asking for 11.4.2 and set up an exclude as you have done for `react-native-maps`

**Comment by AlexandreMaistret** [comment]
@chrisbianca 
Thank you so much ! 
Indeed, I exclude some dependencies for `compile project(':react-native-device-info' )` and everything works perfect !
