### ISSUE TITLE
🔥 NoClassDefFoundError for LibraryVersionComponent on v6 + RN 0.60

### ISSUE THREAD

**Issue by dajaffe** [invertase/react-native-firebase#3054]
## Issue
I'm receiving a NoClassDefFoundError: on com/google/firebase/platforminfo/LibraryVersionComponent for version 6.2.0 with RN 0.60.0. I've had firebase 5.x working on RN 0.59.0. I've tried both on a new RN project, as well as migrating from 5.x to 6. I'd rather not have to revert everything back to old versions and instead get this working. 

The previous issue - https://github.com/invertase/react-native-firebase/issues/2047 - all appears to be for v5.

Tried removing node_modules and npm install'ing, cleaned gradle, etc.  Followed these guides for v6:

https://invertase.io/oss/react-native-firebase/migrating-to-v6
https://invertase.io/oss/react-native-firebase/quick-start/existing-project

Full stack from `adb logcat`:

```
2-29 15:42:27.994 23645 23645 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/platforminfo/LibraryVersionComponent;
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at io.invertase.firebase.ReactNativeFirebaseAppRegistrar.getComponents(ReactNativeFirebaseAppRegistrar.java:34)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at com.google.firebase.components.zzg.<init>(Unknown Source:31)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at com.google.firebase.FirebaseApp.<init>(Unknown Source:114)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source:109)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source:2)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source:28)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source:4)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:1927)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:1902)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:15)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:6578)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at android.app.ActivityThread.-wrap1(Unknown Source:0)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6944)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
12-29 15:42:27.994 23645 23645 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.platforminfo.LibraryVersionComponent" on path: DexPathList[[zip file "/data/app/com.homeautomation-6A98yxnd_Dh3tZa0bCgNLQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.homeautomation-6A98yxnd_Dh3tZa0bCgNLQ==/lib/arm64, /data/app/com.homeautomation-6A98yxnd_Dh3tZa0bCgNLQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
12-29 15:42:27.994 23645 23645 E AndroidRuntime:        ... 21 more
12-29 15:42:59.861 24188 24188 E AndroidRuntime: FATAL EXCEPTION: main
12-29 15:42:59.861 24188 24188 E AndroidRuntime: Process: com.homeautomation, PID: 24188
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "homeautomation",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.26",
    "@fortawesome/free-solid-svg-icons": "^5.12.0",
    "@fortawesome/pro-duotone-svg-icons": "^5.12.0",
    "@fortawesome/pro-light-svg-icons": "^5.12.0",
    "@fortawesome/pro-regular-svg-icons": "^5.12.0",
    "@fortawesome/pro-solid-svg-icons": "^5.12.0",
    "@fortawesome/react-native-fontawesome": "^0.2.0",
    "@react-native-firebase/app": "^6.2.0",
    "@react-native-firebase/messaging": "^6.2.0",
    "axios": "^0.19.0",
    "react": "16.8.6",
    "react-native": "^0.60.0",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-svg": "^9.13.6",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-transitions": "^1.0.12"
  },
  "devDependencies": {
    "@babel/core": "^7.3.3",
    "@babel/runtime": "^7.3.1",
    "@react-native-community/eslint-config": "^0.0.3",
    "babel-jest": "^24.1.0",
    "jest": "^24.1.0",
    "jetifier": "^1.6.5",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-native-clean-project": "^3.3.0",
    "react-native-cli": "^2.0.1",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

#### `firebase.json` for react-native-firebase v6:

None.

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?
Yes

- [ ] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.0")
        classpath 'com.google.gms:google-services:4.3.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

#### `android/app/build.gradle`:

```groovy
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * Use international variant JavaScriptCore
 * International variant includes ICU i18n library and necessary data allowing to use
 * e.g. Date.toLocaleString and String.localeCompare that give correct results
 * when using with locales other than en-US.
 * Note that this variant is about 6MiB larger per architecture than default.
 */
def useIntlJsc = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.homeautomation"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules

    // JSC from node_modules
    if (useIntlJsc) {
        implementation 'org.webkit:android-jsc-intl:+'
    } else {
        implementation 'org.webkit:android-jsc:+'
    }

    implementation "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply plugin: 'com.google.gms.google-services'
```

#### `android/settings.gradle`:

```groovy
rootProject.name = 'homeautomation'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
```

#### `MainApplication.java`:

```java
package com.homeautomation;

import android.app.Application;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      return packages;
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}

```

#### `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.homeautomation">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      
        <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
          <intent-filter>
            <action android:name="com.google.firebase.MESSAGING_EVENT" />
          </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />
    </application>

</manifest>

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 8.08 GB / 15.93 GB
  Binaries:
    Node: 8.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Users\David\AppData\Roaming\npm\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.2, 28.0.3
      System Images: android-25 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
      Android NDK: 19.0.5232133
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: ^0.60.0 => 0.60.6
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/app`
  - `@react-native-firebase/messaging"`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there!
- `npx react-native-clean-project` is the gold standard for actually cleaning things
- this is usually a dependency problem, like something is pulling in the wrong version of firebase, and it's so old it doesn't have that API. That's unexpected, but you can diagnose with `cd android && ./gradlew :app:dependencies` and seeing what comes in. You can manually set the version with a line like this: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh#L29 (but you'll want 24.3.0 as it is current per https://firebase.google.com/support/release-notes/android - I just don't update the script every release)

**Comment by mikehardy** [comment]
I think I see it - you have moved to react-native 0.60 but you are still attempting to use the support libraries, and this change came in around the change to AndroidX. I think the dependencies are pretty crossed up then - you really need to move your project to AndroidX and start using those library versions. The 'make-demo-v6' script I link, if you run it, will generate an AndroidX project with those dependencies, and it will work. If you follow the AndroidX conversion steps (first in AndroidStudio to migrate your project, then since you are on RN60 it will automatically run https://github.com/mikehardy/jetifier to convert any react-native modules you have), then make sure you are on latest firebase modules, this should all work.

I'm going to tentatively close this because I have a script showing it working, which gives me confidence this is a project-specific issue, but I understand you may have some follow-on questions as you work through it. Just know that everything does compile fine, you just need to get the Android side of things current

**Comment by dajaffe** [comment]
Thanks @mikehardy. Turns out react-native-clean-project just wasn't enough. After comparing the gradle settings between make-demo-v6 and my own, I ended up deleting the entire .gradle folder, then re-ran every clean command possible, and that got it working. Just wanted to document this in case anyone else runs into this.

**Comment by mikehardy** [comment]
@dajaffe very interesting! I have personally made a couple PRs to react-native-clean-project because it was close but missed something, and as it stands currently it gets everything I've seen. If you could remember what you removed that it did not, that might be instructive + serve as the basis of PR + save future developers torture

**Comment by dajaffe** [comment]
I actually just ran into it again switching to 5.x.x on RN 0.60 to tinker with the old notifications module. Completely deleting the /android/.gradle folder resolved it. Looks like a PR was opened for deleting that folder early this year but was closed without merging it. I might open a new one on their end at some point.
