### ISSUE TITLE
Having an issue with IOS only messaging().registerForRemoteNotifications() and messaging().getToken() 

### ISSUE THREAD

**Issue by prateekuttreja2020** [invertase/react-native-firebase#7088]
Hi,

I am facing an issue with IOS, its working fine in the android.

After updating @react-native-firebase/messaging & @react-native-firebase/app from 11.5.0 to 17.4.3,  I am having an issue with **messaging().registerForRemoteNotifications()**, it is throwing an error "undefined is not a function" 

Due to this error, messaging().getToken() is throwing an error "You must be registered for remote messages before calling getToken, see messaging().registerDeviceForRemoteMessages()"

I am not able to generate the token.

"react": "18.2.0",
"react-native": "0.71.6",
"@react-native-firebase/app": "17.4.3",
"@react-native-firebase/messaging": "17.4.3",

Any help would be appreciated

**Comment by namikarif** [comment]
I have the same problem
`
messaging().requestPermission({alert: true, badge: true, sound: true}).then(async authStatus => {
                const enabled = authStatus === messaging.AuthorizationStatus.AUTHORIZED || authStatus === messaging.AuthorizationStatus.PROVISIONAL;
                if (enabled) {
                    await messaging().registerDeviceForRemoteMessages();
                    messaging().getToken().then(async token => {
                    }).catch(error => handleError(error));
                    if (Platform.OS === "ios") {
                        messaging().getAPNSToken().then(async token => {
                        });
                    }
                    messaging().onMessage(async (message1) => {
                        Alert.alert(
                            message1.notification.title,
                            message1.notification.body
                        )
                    });
                    messaging().onNotificationOpenedApp((response) => {
                        const data = response.data;
                    });
                    messaging()
                        .getInitialNotification()
                        .then(remoteMessage => {
                            const data = remoteMessage.data;
                        });

                    messaging().setBackgroundMessageHandler(async remoteMessage => {
                    });
                }

            }).catch(error => handleError(error));
`

**Comment by kukuandroid** [comment]
any update on this issue ?

**Comment by srahul9134** [comment]
Facing same issue
