### ISSUE TITLE
Typescript `npm run tsc` errors when deploying firebase functions.

### ISSUE THREAD

**Issue by Jeffreyoboe1** [invertase/react-native-firebase#7093]
## Issue

When trying to deploy firebase functions to firebase, I `cd functions` and use `firebase deploy --only functions`.  This then runs `npm run lint && tsc`, which fails with 14 errors, and then the functions are not deployed.  I believe this change came after upgrading to 17.4.2 (I believe I was on a v16 before) - and it is related to the Aggregation Queries like getting `countFromServer` of documents in a collection.  

I believe this is because we have  interfaces with getter functions, which I believe is not supported in typescript.

---

## Project Files

@react-native-firebase: 17.4.2

ts.config.json file in `functions` directory:  
```
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "typeRoots": ["node_modules/@types"]
  },
  "compileOnSave": true,
  "include": ["src"]
}
```

ts.config.json file in project:  
```

{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "jsx": "react-native",
    "lib": ["dom", "esnext"],
    "moduleResolution": "node",
    "noEmit": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "strict": true,
    "noImplicitAny": true
  },
  "extends": "@tsconfig/react-native/tsconfig.json"
}
```

Errors:  
```
../node_modules/@react-native-firebase/firestore/lib/index.d.ts:881:5 - error TS1131: Property or signature expected.

881     get query(): Query<unknown>;
        ~~~

../node_modules/@react-native-firebase/firestore/lib/index.d.ts:881:9 - error TS1005: ';' expected.

881     get query(): Query<unknown>;
            ~~~~~

../node_modules/@react-native-firebase/firestore/lib/index.d.ts:881:16 - error TS1005: ';' expected.

881     get query(): Query<unknown>;
                   ~

../node_modules/@react-native-firebase/firestore/lib/index.d.ts:881:32 - error TS1005: '(' expected.

881     get query(): Query<unknown>;
                                   ~

../node_modules/@react-native-firebase/firestore/lib/index.d.ts:894:11 - error TS1005: ';' expected.

894     data(): AggregateSpecData<T>;
              ~

../node_modules/@react-native-firebase/firestore/lib/index.d.ts:894:33 - error TS1005: '(' expected.

894     data(): AggregateSpecData<T>;
                                    ~

../node_modules/@react-native-firebase/firestore/lib/index.d.ts:904:5 - error TS1131: Property or signature expected.

904     get query(): Query<unknown>;
        ~~~

../node_modules/@react-native-firebase/firestore/lib/index.d.ts:904:9 - error TS1005: ';' expected.

904     get query(): Query<unknown>;
            ~~~~~

../node_modules/@react-native-firebase/firestore/lib/index.d.ts:904:16 - error TS1005: ';' expected.

904     get query(): Query<unknown>;
                   ~

../node_modules/@react-native-firebase/firestore/lib/index.d.ts:904:32 - error TS1005: '(' expected.

904     get query(): Query<unknown>;
                                   ~

../node_modules/@react-native-firebase/firestore/lib/index.d.ts:921:10 - error TS1005: ';' expected.

921     get(): Promise<AggregateQuerySnapshot<T>>;
             ~

../node_modules/@react-native-firebase/firestore/lib/index.d.ts:921:46 - error TS1005: '(' expected.

921     get(): Promise<AggregateQuerySnapshot<T>>;
                                                 ~

../node_modules/@react-native-firebase/firestore/lib/index.d.ts:922:3 - error TS1128: Declaration or statement expected.

922   }
      ~

../node_modules/@react-native-firebase/firestore/lib/index.d.ts:2265:1 - error TS1128: Declaration or statement expected.

2265 }
     ~


Found 14 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! functions@ build: `npm run lint && tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the functions@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jpadget6/.npm/_logs/2023-05-02T06_40_52_751Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code 2
```

#### `firebase.json` for react-native-firebase v6:

</details>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

#### `AppDelegate.m`:

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `AndroidManifest.xml`:

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `17.4.2`
- **`Firebase` module(s) you're using that has the issue:**
  - `Firestore`
- **Are you using `TypeScript`?**
  - Y 

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by 2sem** [comment]
16.4.5 same why?

```
"typescript": "4.2.4"
```
