### ISSUE TITLE
[🐛] Bug Report Title - 'FirebaseAuth/FirebaseAuth-Swift.h' file not found

### ISSUE THREAD

**Issue by Tarun24RN** [invertase/react-native-firebase#8066]

**Comment by mikehardy** [comment]
Unsupported build configuration not using use_frameworks.

Also, please do not post issues with only a title.

**Comment by Tarun24RN** [comment]
> Unsupported build configuration not using use_frameworks.
> 
> Also, please do not post issues with only a title.

After using   use_frameworks! I get this issue 
Undefined symbols for architecture arm64:
  "_FIRConsentStatusDenied", referenced from:
      -[RNFBAnalyticsModule setConsent:resolver:rejecter:] in RNFBAnalyticsModule.o
  "_FIRConsentStatusGranted", referenced from:
      -[RNFBAnalyticsModule setConsent:resolver:rejecter:] in RNFBAnalyticsModule.o
  "_FIRConsentTypeAdPersonalization", referenced from:
      -[RNFBAnalyticsModule setConsent:resolver:rejecter:] in RNFBAnalyticsModule.o
  "_FIRConsentTypeAdStorage", referenced from:
      -[RNFBAnalyticsModule setConsent:resolver:rejecter:] in RNFBAnalyticsModule.o
  "_FIRConsentTypeAdUserData", referenced from:
      -[RNFBAnalyticsModule setConsent:resolver:rejecter:] in RNFBAnalyticsModule.o
  "_FIRConsentTypeAnalyticsStorage", referenced from:
      -[RNFBAnalyticsModule setConsent:resolver:rejecter:] in RNFBAnalyticsModule.o
  "_OBJC_CLASS_$_FIRAnalytics", referenced from:
       in RNFBAnalyticsModule.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

All these are coming when i upgrade library version from 19 to 21.

**Comment by mikehardy** [comment]
Google mikehardy rnfbdemo and examine make-demo.sh

Fully automatic build demonstrator. Works.

You have a local problem specific to your project and have not provided information required to fix

Google "stackoverlow how to ask"
