### ISSUE TITLE
[📚] Documentation Issue - FilterFunction

### ISSUE THREAD

**Issue by val089** [invertase/react-native-firebase#7134]
## Documentation Feedback

Where can I find Filter instance to do multiple filter? I cant import it from anywhere.

https://rnfirebase.io/firestore/usage

I want to create something like this:

const snapshot = await firestore()
.collection('Users')
.where(Filter.and(Filter('user', '==', 'Tim'), Filter('email', '==', '[tim@example.com](mailto:tim@example.com)')))
.get();

**Comment by illlama** [comment]
@pafry7 Is this problem still in progress?

**Comment by coycoylaniba** [comment]
i hope that they will fix this

**Comment by val089** [comment]
I'm waiting too.

**Comment by pafry7** [comment]
> @pafry7 Is this problem still in progress?

We are waiting for the reviewer

**Comment by mikehardy** [comment]
Really sorry for the delay!

Thank you so much @falleco for proposing PR #7124 to fix it and @pafry7 for the review!

It looks good to me and I am inclined to merge it but I will wait for a couple hours in the hope someone else here has a moment to glance over the final changes made in the last few hours to make sure they all look good?

**Comment by pafry7** [comment]
@mikehardy I've patched my project with the changes from PR and no problems so far.

**Comment by mikehardy** [comment]
Excellent - thanks again @pafry7 for the quality help - will merge that PR then, I'm queueing it with a batch of PRs that will all release today. Cheers!

**Comment by emilstepanian** [comment]
Anybody else still having problems? When I import Filter and try to use 'and' or 'or' functions, I get "TypeError: undefined is not a function" errors

**Comment by markbarton** [comment]
Where do you import Filter from? has anyone got a simple example?   Thanks

**Comment by emilstepanian** [comment]
> Where do you import Filter from? has anyone got a simple example? Thanks

I import from @react-native-firebase/firestore, but yeah, I still can't really use it

**Comment by illlama** [comment]
After I installed 18.3.0 (maybe after [18.0.0](https://github.com/invertase/react-native-firebase/pull/7124) is ok) errors are solved
I can use `import { Filter } from '@react-native-firebase/firestore';` and no errors anymore

**Comment by illlama** [comment]
I'm still getting struggle after updated from 17.5.0 to 18.3.0
using like this
```
import firestore, { Filter } from '@react-native-firebase/firestore';

...

.collection(fbPinnedList)
    .where(Filter('location.longitude', '<=', longitude + searchSize))
```

or 

```
.collection(fbPinnedList)
    .where(
      Filter.and(
        Filter('location.longitude', '<=', longitude + searchSize),
        Filter('location.longitude', '>=', longitude - searchSize)
      )
    )
```

And I think problem is Filter is detected as undefined.
Because I can get bellow logs

```
TypeError: undefined is not a function
or
TypeError: Cannot read property 'and' of undefined
```

Can I get any hint?

**Comment by jnwright** [comment]
trying to use Filter.or and getting a similar error `TypeError: Cannot read property 'or' of undefined`

**Comment by danielkv** [comment]
I've got to solve the problem. I created a patch to fix the issue. 

It's happening because the `Filter` is not exported. I just exported the `Filter` from the `index.js`. I'll try to open a PR to fix it. Not sure if I can do it today though.

**Comment by matmac** [comment]
Having the same problem here, Filter does not work and shows an error.

**Comment by gorkemunluyurt** [comment]
> Having the same problem here, Filter does not work and shows an error.

I'm trying to use filter.or and I get the same error. Did you find a solution?

**Comment by mahesh-agrawal-313** [comment]
@danielkv sir, i tried exporting the filter from the index.js file but it also did not work. Can you please help with a patch log.

**Comment by shrads12** [comment]
If anyone is still struggling with this, the following example might help. It worked for me

```
import firestore from "@react-native-firebase/firestore";

    const snapshot = await firestore()
      .collection<Connection>("connections")
      .where(
        firestore.Filter.or(
          firestore.Filter("sender", "==", user.email),
          firestore.Filter("receiver", "==", user.email)
        )
      )
      .get();
```

**Comment by artem-alek** [comment]
still an issue

**Comment by mikehardy** [comment]
If someone posts a PR we can merge it + release 🙏

**Comment by haeniya** [comment]
Still an issue

**Comment by haeniya** [comment]
Still relevant

**Comment by mikehardy** [comment]
If someone posts a PR we can merge it + release 🙏

**Comment by mahesh-agrawal-313** [comment]
> @shrads12 haven't worked for me.
> 
> > @danielkv sir, i tried exporting the filter from the index.js file but that also did not work. Can you please help with a patch log.
> 
> @mahesh-agrawal-313 I'm sorry for the delay. This is the patch that I've created (I'm using yarn v3+):
> 
> @react-native-firebase-firestore-npm-18.3.0-0a6be6db66.patch
> 
> ```
> diff --git a/lib/index.d.ts b/lib/index.d.ts
> index 74872beb39b215c95b3ae89691d19c60a7991491..536be01e02452f1a39947ed9838cd1d30698d91e 100644
> --- a/lib/index.d.ts
> +++ b/lib/index.d.ts
> @@ -2340,7 +2340,7 @@ export const firebase: ReactNativeFirebase.Module & {
>    ): ReactNativeFirebase.FirebaseApp & { firestore(): FirebaseFirestoreTypes.Module };
>  };
>  
> -export const Filter: FilterFunction;
> +export const Filter: FirebaseFirestoreTypes.FilterFunction;
>  
>  export default defaultExport;
>  
> diff --git a/lib/index.js b/lib/index.js
> index 7b7e8167ff80bf77fdc879992038208f85c9de8e..e784737d688a121ce6f3ca3713d90a38f9d4c355 100644
> --- a/lib/index.js
> +++ b/lib/index.js
> @@ -376,3 +376,5 @@ export default createModuleNamespace({
>  // firestore().X(...);
>  // firebase.firestore().X(...);
>  export const firebase = getFirebaseRoot();
> +
> +export { Filter } from './FirestoreFilter'
> ```

error does not come but there is no response after using filter.or or filter.and function. no success or failure.

**Comment by danielkv** [comment]
@shrads12 I'm sorry for the delay. I'm actually not usi5the patch anymore. After updating the version to 18.5+ it worked.

**Comment by haeniya** [comment]
I believe this is still an issue.

**Comment by haeniya** [comment]
Is this fixed now?

**Comment by janroures** [comment]
still an issue. using `firestore.Filter` works

**Comment by oleksii00ishchenko** [comment]
same problem

**Comment by sirusbaladi** [comment]
firestore.Filter doesn't work for me. I have 18.0.0. undefined is not a function.

**Comment by thisisgit** [comment]
This is issue is caused by only exporting type of `Filter` but not exporting Filter function itself:
https://github.com/invertase/react-native-firebase/blob/ca07cadd592487102b035a24b55f593f065ef4a5/packages/firestore/lib/index.d.ts#L2345

I'm not really familiar on working with `*.d.ts` files but AFAIK `*.d.ts` are only responsible for supporting types of `js` files of the same name.
So when I checked [`index.js`](https://github.com/invertase/react-native-firebase/blob/main/packages/firestore/lib/index.js) of the same directory, I can't find anywhere that exports the `Filter` function.

Since `Filter` function is defined in `FirestoreFilter.js`, I tried re-exporting the function from `index.js` and it worked:
```js
// ...
export { Filter } from './FirestoreFilter';
// ...
```

However I couldn't open a PR since I couldn't push my working branch to remote. I see this error:
```
remote: Permission to invertase/react-native-firebase.git denied to thisisgit
fatal: unable to access 'https://github.com/invertase/react-native-firebase.git/': The requested URL returned error: 403
```
I couldn't find instruction about authentication in the guideline. Is there something I'm missing? cc @mikehardy
