### ISSUE TITLE
absl/numeric/int128_have_intrinsic.inc' file not found 

### ISSUE THREAD

**Issue by sombizbuzzz** [invertase/react-native-firebase#3031]
i am getting this error .unable to build .
/Pods/Headers/Public/abseil/absl/numeric/int128.h:726:10: fatal error: 'absl/numeric/int128_have_intrinsic.inc' file not found

here is my pod version 

 # Required by RNFirebase

  pod 'Firebase/Core', '~> 6.13.0'
  pod 'Firebase/Auth', '~> 6.13.0'
  pod 'Firebase/Database', '~> 6.13.0'
  pod 'Firebase/Functions', '~> 6.13.0'
  pod 'Firebase/DynamicLinks', '~> 6.13.0'
  pod 'Firebase/Firestore', '~> 6.13.0'
  pod 'Firebase/Messaging', '~> 6.13.0'
  pod 'Firebase/RemoteConfig', '~> 6.13.0'
  pod 'Firebase/Storage', '~> 6.13.0'
  pod 'Firebase/Performance', '~> 6.13.0'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'

and 

 "react-native-firebase": "^5.6.0",
  "react": "16.8.3",
    "react-native": "0.59.8",

let me whats the why its coming 

https://stackoverflow.com/questions/59442084/absl-numeric-int128-have-intrinsic-inc-file-not-found-in-react-native-firebase

**Comment by mikehardy** [comment]
let me know if any of the solutions here work 
https://stackoverflow.com/questions/58908869/swift-firestore-absl-numeric-int128-have-intrinsic-inc-file-not-found

**Comment by sombizbuzzz** [comment]
@MBagory  none of working , i tried before posting here all these .

**Comment by monkibraum** [comment]
+1, same situation. 

```
    "@react-native-firebase/app": "^6.2.0",
    "@react-native-firebase/auth": "^6.2.0",
    "@react-native-firebase/firestore": "^6.2.0",
    "@react-native-firebase/messaging": "^6.2.0",
    "react-native": "0.61.5",
```
```
ios/Pods/Headers/Public/abseil/absl/numeric/int128.h:726:10: fatal error: 'absl/numeric/int128_have_intrinsic.inc' file not found
#include "absl/numeric/int128_have_intrinsic.inc"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by mikehardy** [comment]
please confirm you have run 'cd ios && pod repo update' and abseil was fully updated

**Comment by mikehardy** [comment]
I run pod outdated to check if there updates periodically, then you can alternatively check the github repo of cocoapods for that pod and start backing versions down perhaps, in case they have broken something with current release

either way, this is an upstream issue, in the firebase SDKs and their dependencies. People using react-native-firebase will be affected, but that's not our software, we can't fix it

**Comment by monkibraum** [comment]
@mikehardy Thanks! after upgrading cocoapods to 1.8.4 (mine was 1.5.x) and reinstalling pods, it works.

```
sudo gem install cocoapods -v 1.8.4 
cd ios && pod deintegrate
pod clean
pod install
react-native run-ios
```

**Comment by mikehardy** [comment]
@monkibraum glad that worked! You will be internet famous if you post that to the relevant stack overflow threads as well :-)

I'm going to close this as I could never reproduce (I was already current) and you appear to have found the reason

**Comment by momodevelopment** [comment]
> https://stackoverflow.com/questions/58908869/swift-firestore-absl-numeric-int128-have-intrinsic-inc-file-not-found

I then dropped into terminal an updated cocoapods manually

sudo gem install cocoapods
and then navigated to the project folder and then
pod install

It's work for me. 
    I use Xcode version 11.1 (11A1027) , 
   # Firebase. Specify version 6.6
    pod 'Firebase/Core', '~> 6.13.0'
    pod 'Firebase/Messaging', '~> 6.13.0'
    pod 'Firebase/Performance', '~> 6.13.0'
    pod 'Firebase/RemoteConfig', '~> 6.13.0'
    pod 'Firebase/Firestore', '~> 6.13.0'
    pod 'Firebase/Auth', '~> 6.13.0'
    pod 'Firebase/Storage', '~> 6.13.0'

Many thanks @mikehardy

**Comment by markymark1988** [comment]
This is what worked for me https://stackoverflow.com/a/61516806/1159930
