### ISSUE TITLE
[🐛] Bug  Use of undeclared identifier 'FIRApp' in AppDelegate.mm (New Architecture).

### ISSUE THREAD

**Issue by AdhamMahmoud98** [invertase/react-native-firebase#6625]
I am trying to integrate with the new architecture of react native v0.70.3. In iOS the AppDelegate.m is removed and AppDelegate.mm is used but I can't use [FIRApp configure]; to initialize firebase in the app.

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];  //Use of undeclared identifier 'FIRApp'
  ...............
}

But the build is failing and the error is Use of undeclared identifier 'FIRApp'. Anyone has any idea on how to tackle this issue ?

**Comment by mikehardy** [comment]
Hey @AdhamMahmoud98 - there is no problem working with react-native 0.70.x and AppDelegate.mm vs AppDelegate.m

You initialize them the same way, with an import and then a call to configure.

Here's a demo that does it from scratch and works against react-native 0.70.x:

https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

These 2 lines in particular are where I slice in the import, and then slice in the `FIRApp configure`:

https://github.com/mikehardy/rnfbdemo/blob/ce97efd7e3f9e503317d6c92ed151e4daf7670fe/make-demo.sh#L83-L87

It's documented as well. 

https://rnfirebase.io/#configure-firebase-with-ios-credentials

Yes, it says AppDelegate.m but there is zero difference with .mm

Given I've provided a working reproduction that I test regularly which you may execute to see it works, I know this is not a problem with the module thus there is no further action I can take here, so I'll close this

**Comment by mikehardy** [comment]
You will ned to read the docs carefully though, as you mention "new architecture" and you must understand that facebook built the new architecture in a way that is not yet compatible with `use_frameworks!` in your Podfile and react-native-firebase **strictly requires `use_frameworks`**

So react-native-firebase is not compatible with new architecture - it will work fine on current react-native you just cannot enable fabric / new architecture


> New Architecture: Fabric is not compatible with use_frameworks!. Community support to help fix use_frameworks support for New Architecture is welcome!

**Comment by AdhamMahmoud98** [comment]
Hi @mikehardy  I solved the issue. It was an import issue :). For anyone who encounters this issue please make sure that #import <Firebase.h> is placed ABOVE #if RCT_NEW_ARCH_ENABLED in appdelegate.mm otherwise it will cause the same issue

**Comment by ken0x0a** [comment]
@mikehardy 

I successfully build iOS app without `use_frameworks!` with following.
I hope RNFB will support New Architecture soon!!

```ruby
  $static_framework = [
    "GoogleUtilities", # ERROR on Xcode: Cycle in dependencies between targets ... and 'GoogleUtilities'; building could produce unreliable results.
  ]
  $modular_headers = [
    "FirebaseCore", # ERROR on Xcode: Module 'FirebaseCore' not found
    "GoogleUtilities", # ERROR on pod install: The Swift pod `FirebaseCoreInternal` depends upon `GoogleUtilities`, which does not define modules.
  ]

  $modular_headers.each do |name|
    @current_target_definition.set_use_modular_headers_for_pod(name, true)
  end

  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if $static_framework.include?(pod.name)
        def pod.build_type;
          Pod::BuildType.static_framework
        end
      end
    end
  end
```

**Comment by mikehardy** [comment]
I will not condone or support any use of react-native-firebase on iOS without use_frameworks.

You can try a few workarounds to try to make it work but if you use firebase-ios-sdk (we do) they require use_frameworks *so that is our only supported configuration*

You will likely find that storage and functions do not work as expected, and regardless, you won't be able to access support here for any issues you have related to build failures.

**Comment by ken0x0a** [comment]
`@current_target_definition.set_use_modular_headers_for_pod` is the function, called with `use_moduler_headers!`,
`Pod::BuildType.static_framework` is the result of `use_frameworks! :linkage => :static` (only for single package).

So, requires `use_frameworks!` means, requires to set `Pod::BuildType.static_framework` for some modules.

I might not correct as I read only partial source code of Cocoapods.

**Comment by mikehardy** [comment]
If you believe this is a valid technical approach, please bring it up on the firebase-ios-sdk repository as a request for clarification on the validity of the alternate style combined with request for update to their documentation. It may be valid, but I have experienced compile failures and corresponding high support load *in this repo* from people attempting to dodge the use_frameworks requirement, and it is currently not supported in the absence of official guidance in firebase-ios-sdk

**Comment by mikehardy** [comment]
It should also be noted that this statement:

> I hope RNFB will support New Architecture soon!!

Is the same (based on current supported configurations here...) as saying "I hope New Architecture will support use_frameworks soon", which is not under our control
