### ISSUE TITLE
[🐛] TypeError: _this.native.configureAuthDomain is not a function (it is undefined)

### ISSUE THREAD

**Issue by selimjouan** [invertase/react-native-firebase#7619]
## Issue

Since upgrading from 18.7.3 to 18.8.0, my app dev client cannot launch, I got this error right after startup:
```
 ERROR  TypeError: _this.native.configureAuthDomain is not a function (it is undefined), js engine: hermes
```
Everything was working fine before.
I know 18.8.0 introduced auth domain, but there is nothing indicating a required change in the code nor a breaking change.

---

## Environment
expo v50
react v0.73.4

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 18.8.0 (all react-native-firebase packages have the same version)
- **`Firebase` module(s) you're using that has the issue:**
  - auth
- **Are you using `TypeScript`?**
  - Yes: 5.3.3

</p>

**Comment by mikehardy** [comment]
> _this.native.configureAuthDomain is not a function

Looks like the javascript doesn't match the native code that's built.

You mention "dev client" which smells like Expo.
Typical Expo error is "I forgot to rebuild my native code", which would lead to this error message

**Comment by selimjouan** [comment]
I fixed it with a fresh build using exact version matching
```
"@react-native-firebase/app": "18.8.0",
"@react-native-firebase/app-check": "18.8.0",
"@react-native-firebase/auth": "18.8.0",
"@react-native-firebase/crashlytics": "18.8.0",
```
Previous build was on "^18.8.0", which must have used an older cached version I guess

**Comment by TheSavageDev** [comment]
I locked our versions to 18.7.3 and it works. So something in maybe +18.8.0 doesn't work well with Expo.

**Comment by mikehardy** [comment]
@TheSavageDev something about Expo is not clearing cache correctly for the build so that you get the firebase-ios-sdk underlying version that has the new symbol required by our javascript layer. It's a "javascript layer" vs "native layer" incompatibility which here is always either a) your native build cache needs to be purged so it is rebuilt and native matches or b) you have pinned your firebase-ios-sdk version in your Podfile and have not updated it / should remove the pin

**Comment by adriaanbalt** [comment]
I'm encountering the same error as above on version `19.0.0` and `18.8.8`.  I am using Expo SDK 50 managed flow.  Ive cleared the native build cache.  Since I'm in the managed flow I do not have a Podfile.  

Also note that when I downgrade back to `18.7.3` I'm able to run a build without this error but I have issues with Auth permissions in Firebase Storage.  Not sure if that is related though.  The name of the function that is causing problems seems related though "configureAuthDomain".

**Comment by jakechao-zeal** [comment]
Hi @adriaanbalt did you find any resolution to this issue when trying to upgrade to versions higher than `18.7.3 `? Experiencing a similar problem when trying to upgrade to `18.9.0`
