### ISSUE TITLE
[🐛] rn@0.76.0 No member named 'memory_order_relaxed' in 'std::memory_order';

### ISSUE THREAD

**Issue by efstathiosntonas** [invertase/react-native-firebase#8082]
After upgrading to 0.76 with Fabric enabled, for some reason `leveldb-library` `env_posic.cc` file throws this error:

`No member named 'memory_order_relaxed' in 'std::memory_order'; did you mean 'std::memory_order_relaxed'?`

@mikehardy I think this is an upstream issue, it seems that the `leveldb-library` version is `1.22` and this has changed in version `1.23`. I've applied the suggested changes from Xcode and the error went away. I'm opening the issue here so other devs are aware, shall we open an issue on upstream? 

ps. Sorry for skipping issue template, it seems unrelated to us here.
ps2. Why on earth the new arch throws this error?? 🤔

**Comment by efstathiosntonas** [comment]
leaving this here: 

https://github.com/firebase/firebase-ios-sdk/blob/36da449b15619d301302faeba639c7893d576220/Package.swift#L161=#L164

**Comment by russellwheatley** [comment]
FirebaseDatabase.podspec does allow `v1.23` which is what RNFB is using: https://github.com/firebase/firebase-ios-sdk/blob/main/FirebaseDatabase.podspec#L49

You might wish to open an issue on firebase-ios-sdk repo if you think the SPM version should allow `v1.23` but I wonder if there is a reason for the discrepancy.

**Comment by efstathiosntonas** [comment]
@russellwheatley podspec indeed does allow it but on the other hand SPM does not and I guess that SPM takes precedence over it thus we're "stuck" on 1.22. 

It's really weird that the issue arised on rn@0.76.0 new arch. On 0.75.4 Paper it works fine.


<details>
  <summary>Podifle.lock</summary>

  ```
  - Firebase/Analytics (11.4.0):
    - Firebase/Core
  - Firebase/AppCheck (11.4.0):
    - Firebase/CoreOnly
    - FirebaseAppCheck (~> 11.4.0)
  - Firebase/Auth (11.4.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 11.4.0)
  - Firebase/Core (11.4.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 11.4.0)
  - Firebase/CoreOnly (11.4.0):
    - FirebaseCore (= 11.4.0)
  - Firebase/Database (11.4.0):
    - Firebase/CoreOnly
    - FirebaseDatabase (~> 11.4.0)
  - Firebase/DynamicLinks (11.4.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (~> 11.4.0)
  - Firebase/Functions (11.4.0):
    - Firebase/CoreOnly
    - FirebaseFunctions (~> 11.4.0)
  - Firebase/Messaging (11.4.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 11.4.0)
  - FirebaseAnalytics (11.4.0):
    - FirebaseAnalytics/AdIdSupport (= 11.4.0)
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/MethodSwizzler (~> 8.0)
    - GoogleUtilities/Network (~> 8.0)
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
    - nanopb (~> 3.30910.0)
  - FirebaseAnalytics/AdIdSupport (11.4.0):
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - GoogleAppMeasurement (= 11.4.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/MethodSwizzler (~> 8.0)
    - GoogleUtilities/Network (~> 8.0)
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
    - nanopb (~> 3.30910.0)
  - FirebaseAppCheck (11.4.0):
    - AppCheckCore (~> 11.0)
    - FirebaseAppCheckInterop (~> 11.0)
    - FirebaseCore (~> 11.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
  - FirebaseAppCheckInterop (11.4.0)
  - FirebaseAuth (11.4.0):
    - FirebaseAppCheckInterop (~> 11.0)
    - FirebaseAuthInterop (~> 11.0)
    - FirebaseCore (~> 11.4)
    - FirebaseCoreExtension (~> 11.4)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GTMSessionFetcher/Core (< 5.0, >= 3.4)
    - RecaptchaInterop (~> 100.0)
  - FirebaseAuthInterop (11.4.0)
  - FirebaseCore (11.4.0):
    - FirebaseCoreInternal (~> 11.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/Logger (~> 8.0)
  - FirebaseCoreExtension (11.4.0):
    - FirebaseCore (~> 11.0)
  - FirebaseCoreInternal (11.4.0):
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
  - FirebaseDatabase (11.4.0):
    - FirebaseAppCheckInterop (~> 11.0)
    - FirebaseCore (~> 11.0)
    - FirebaseSharedSwift (~> 11.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - leveldb-library (~> 1.22)
  - FirebaseDynamicLinks (11.4.0):
    - FirebaseCore (~> 11.0)
  - FirebaseFunctions (11.4.0):
    - FirebaseAppCheckInterop (~> 11.0)
    - FirebaseAuthInterop (~> 11.0)
    - FirebaseCore (~> 11.4)
    - FirebaseCoreExtension (~> 11.4)
    - FirebaseMessagingInterop (~> 11.0)
    - FirebaseSharedSwift (~> 11.0)
    - GTMSessionFetcher/Core (< 5.0, >= 3.4)
  - FirebaseInstallations (11.4.0):
    - FirebaseCore (~> 11.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - PromisesObjC (~> 2.4)
  - FirebaseMessaging (11.4.0):
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - GoogleDataTransport (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/Reachability (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - nanopb (~> 3.30910.0)
  - FirebaseMessagingInterop (11.4.0)
  - FirebaseSharedSwift (11.4.0)
  ```
</details>

**Comment by mikehardy** [comment]
I had the same problem!! It was the last thing left for me to qualify rn76 while it was in RV. Check my rn76 branch in my rnfbdemo repo and you can see a patch-hack that makes it work but I haven't figured a true fix yet

**Comment by russellwheatley** [comment]
@efstathiosntonas - I don't think SPM interferes with cocoapods. They are two separate things.

It is more likely that cocoapods doesn't have a release for 1.23.0 which bears out when you look at the Specs: https://github.com/CocoaPods/Specs/tree/master/Specs/a/d/a/leveldb-library

That last release was 1.22.5

**Comment by efstathiosntonas** [comment]
It seems 1.23 is broken? 🫨 

https://github.com/google/leveldb/issues/1101

**Comment by efstathiosntonas** [comment]
> rn76 while it was in RV.

@mikehardy are you coding on an [RV](https://www.motorcyclenews.com/bike-reviews/suzuki/rv125-van-van/2003/)? 🤣

**Comment by mikehardy** [comment]
> > rn76 while it was in RV.
> 
> @mikehardy are you coding on an [RV](https://www.motorcyclenews.com/bike-reviews/suzuki/rv125-van-van/2003/)? 🤣

Sorry - was typing on cell phone from a tiny backpacker hostel in Baños Ecuador while doing the [Vuelta Nacional Ecuador](https://www.facebook.com/halconesunidos23/posts/pfbid02pBVGvPvyXvTqEM2HQ6UNUA1dDHQbeXzduiffpACi22ZKoEYwHshhkfziHAPWgwVyl?__cft__[0]=AZXKPmKer2p6n1kwq6VruQNUcrD7jtFmLo-hdwWsZKO2vaZmecp_rlKJGahzLeb7iqgAlDULix-Sfp0VeosgSj0990jeQv43ybzTI4wMbSoVyiitHRwN7gto-sYky0ApWKIjvRjGiSX_lyF_kcw1iL8FzaU_N-oZ6y86p4N2v2n71mavN_ugyCA0z-oeG4MA89qr1j2eNkixmVBeTx9jBCm0w57Nm64RLAkdU-s1Xuqg1Q&__tn__=%2CO%2CP-R) - so, almost 😆  ? RC of course

**Comment by efstathiosntonas** [comment]
@mikehardy what shall we do? open an issue on upstream? If yes, can you please do so since you know the intenals better than me?

**Comment by matinzd** [comment]
@efstathiosntonas 

Which upstream? firebase-ios-sdk or leveldb?

**Comment by mikehardy** [comment]
The thing is, 1.23 tag has the same lines (they are just a little lower)

https://github.com/google/leveldb/blob/99b3c03b3284f5886f9ef9a4ef703d57373e61be/util/env_posix.cc#L839C1-L841

What I noticed when I first saw this is that the only lines that have a problem are the ones that are wrapped with:

```
#if !defined(NDEBUG)
```

So I have a different hunch: I think those lines have been broken for a long long time and indeed they were added 6 years ago: https://github.com/google/leveldb/blame/1.22/util/env_posix.cc#L816-L818

So why are they breaking now? Combine that question with the idea the only 2 places that have problems are wrapped with a compiler "NDEBUG" guard and what I think is, that symbol is now being defined by react-native 0.76, and it is just a terribly unlucky coincidence that there was a symbol collision

So, 3 things, I think:

1- leveldb has a bug, needs a PR + release + adoption of release inside react-native
2- perhaps we can cookup a postinstall script just for the react-native-firebase pods that use leveldb - until 1 above is done - that *removes* the NDEBUG symbol from the compile flags? Is that possible? Or perhaps a post-install script that applies the source patch for now  like my rn76 make-demo project does?
3- people need to prefix the symbols they use at all times when things aren't namespaced (assuming my hunch here is correct - can be confirmed by looking at react-native for that symbol. These should be REACT_NATIVE_NDEBUG and LEVELDB_NDEBUG, in my humble opinion.

Indeed, looks like they are the ones defining it, and the intention I think was to define it for both architectures but I suspect there is an extra bug where that didn't happen, and it is only defined for Fabric for some reason, so it only triggers now:

https://github.com/facebook/react-native/commit/1a0e1741c0ab4f22b57a6a7ee86ff4287fa09103

**Comment by mikehardy** [comment]
Looks like leveldb already has this patched, it just hasn't been released yet, so we need workarounds until 1.24 comes out, but at least the source code is fixed...

I begged for a release here:
https://github.com/google/leveldb/pull/965#issuecomment-2436371816

**Comment by efstathiosntonas** [comment]
> @efstathiosntonas
> 
> Which upstream? firebase-ios-sdk or leveldb?

 leveldb, don't think firebase-ios-sdk can do much about this unless it pushes them to team up internally with leveldb maintainers and provide a fix faster 🤔

**Comment by simonbengtsson** [comment]
Made a cocoa pods post install script to apply the patch discussed above. Not sure this is the best way to approach patches like this, but seems to work for me at least.

```ruby
target 'App' do
  # ...
  post_install do |installer|
      # Issue info: https://github.com/invertase/react-native-firebase/issues/8082
      # Patch info: https://github.com/google/leveldb/pull/965
      leveldb_posix_file = 'Pods/leveldb-library/util/env_posix.cc'
      if File.exist?(leveldb_posix_file)
        old_contents = File.read(leveldb_posix_file)
        new_contents = old_contents.gsub(/std::memory_order::memory_order_relaxed/, "std::memory_order_relaxed")
        File.chmod(0777, leveldb_posix_file)
        File.open(leveldb_posix_file, "w") { |file| file.puts new_contents }
      end
  end
end
```

**Comment by mikehardy** [comment]
@simonbengtsson fantastic - that looks like *exactly* the necessary post_install chunk for people to work around this as needed. The chmod is needed (in case anyone was curious), so the combo of chmod + replace is the minimal + correct solution. It is not great to use workarounds like this, sure, but this one should be effective for anyone that needs it. Thanks for posting

**Comment by mikehardy** [comment]
I did a little more digging as I could not see cocoapods-related files in the google/leveldb repo, it turns out there is a fork living in firebase/leveldb and that is the source for our dependency when using firebase-ios-sdk

I have proposed a pull request with the needed change from upstream google/leveldb into the firebase/leveldb repository here: https://github.com/firebase/leveldb/pull/15

Perhaps @ncooke3 - who appears to maintain the repo currently - or @paulb777 who is also associated will take pity on us poor react-native souls dealing with build flags we're not in control of that are exposing these non-C++20 symbols 🙏

**Comment by mikehardy** [comment]
In order to use that pull request, which I just confirmed works to fix leveldb-library in react-native context with NDEBUG defined, you may add this to your Podfile:

```ruby
  pod 'leveldb-library', :git => 'https://github.com/mikehardy/leveldb.git', :commit => 'dc346ebc29fa755f5193dfc9d0a9f463b42a9d2b'
```

It is the exact same effect as the post_install block above - just alters those two lines vs the current released version. Either will work for anyone

**Comment by LA-Johan** [comment]
Appreciate all the effort people have spent on this. As someone who's excited to upgrade to RN 0.76 but in no immediate rush, is there an official fix to this library that's coming in the near-ish future or will the podfile addition above be required for the foreseeable future?

**Comment by mikehardy** [comment]
The only people that can answer that are the firebase-ios-sdk folks that work diligently upstream to shepherd their various repos - you could perhaps add a reaction to my PR upstream to indicate you're interested in it, and hopefully it is released soon. All I can say is the Podfile changes (direct pod commit hash ref, or postinstall block) will be required until there's a release, but I can't say when a release will happen

**Comment by mikehardy** [comment]
Upstream firebase-ios-sdk team has already reviewed and merged the necessary PR, great news and quite quick IMHO. They're testing overnight to make sure it meets all standards but it's on track for release.

Next update here will hopefully be the final one as it resolves and closes 🤞

**Comment by raduciobanu22** [comment]
> Upstream firebase-ios-sdk team has already reviewed and merged the necessary PR, great news and quite quick IMHO. They're testing overnight to make sure it meets all standards but it's on track for release.
> 
> Next update here will hopefully be the final one as it resolves and closes 🤞

Came here because of the same issue in my Flutter app. Many thanks for your efforts!

**Comment by mikehardy** [comment]
@KevinSinSH that is unrelated. I see that as well in a test-integration I'm doing now with cocoapods updated to the new 1.16.0 release and the new xcodeproj 1.26.0 gem. You'll want to back those down to cocoapods 1.15.2 and xcodeproj 1.25.0 I believe.

Ref https://github.com/facebook/react-native/pull/47237

**Comment by mikehardy** [comment]
The leveldb-library cocoapod version with the fix was just released. I confirm it works.

**you will want to remove your Podfile.lock and `pod install` again in order to get the fix**

You should see 

> Installing leveldb-library (1.22.6)

...and that means you have the fix and this issue is closed

🚂  ✅ 

----

If you see some other errors like:

> Undefined symbols for architecture arm64
> ❌   "absl::lts_20240116::CHexEscape(absl::lts_20240116::string_view)", referenced from:

**those errors are unrelated**

If you see those you have likely updated to cocoapods 1.16.0 (from 1.15.2) and/or xcodeproj 1.26.0 (from 1.25.0). You will want to use cocoapods 1.15.2 + xcodeproj 1.25.0 in order to build react-native successfully, reference https://github.com/facebook/react-native/pull/47237

**Comment by KevinSinSH** [comment]
@mikehardy Much appreciated for your answer. Unfortunately, after down to cocoapods 1.15.2 another bunch of errors show up. May I know if I am I stuck at this moment until fixed? 
![image](https://github.com/user-attachments/assets/397aa818-a722-48c0-ae31-d38aa33c373d)

**Comment by mikehardy** [comment]
@KevinSinSH not related to this issue, not going to discuss here and pollute people's inbox / notifications

This issue is closed, there is no longer a problem with "No member named 'memory_order_relaxed'"

**Comment by efstathiosntonas** [comment]
@mikehardy thank you for your efforts on this!  It was fixed really fast 😎

**Comment by phaiminh** [comment]
@mikehardy so this error

Undefined symbols for architecture arm64
❌ "absl::lts_20240116::CHexEscape(absl::lts_20240116::string_view)", referenced from:

is not coming from leveldb-library. I got that error after update to 1.22.6. Do I have to update firebase sdk as well? Many thanks for your support.
