### ISSUE TITLE
[Android] default App not initialized when using Gradle 3.3.2 / React-Native 0.59.1

### ISSUE THREAD

**Issue by Barbiero** [invertase/react-native-firebase#1994]
## Issue

I tried upgrading to React-Native v0.59.1, but when I open my newly-upgraded app the following error message shows up:

> The [[DEFAULT]] firebase app has not been initialized!

#766 is an issue that shows people with a related problem, but seems to have different root causes; either way, some people were asking for the issue to be reopened(which IMO is a mistake since this is a different problem)

This occurs on a newly-created RN project as well, so it's probably an issue with RNF + the upgraded build systems on android.

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
```

#### `android/app/build.gradle`:

```groovy
```

#### `android/settings.gradle`:

```groovy
```

#### `MainApplication.java`:

```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `Android API 28`
- **Operating System:**
  - [X] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Android Studio 3.3.2`
- **`React Native` version:**
  - `0.59.1`
- **`React Native Firebase` library version:**
  - `5.2.3`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [ ] No
  - [X] Yes, version: `3.3.3333`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by otaviosoares** [comment]
What's is your google-services version? I got it working on 0.59 by upgrading it to 4.2.0.

**Comment by Barbiero** [comment]
> What's is your google-services version? I got it working on 0.59 by upgrading it to 4.2.0.

I was previously using version 4.1.0, updating to 4.2.0 fixed my problem. Thank you!

I believe the official RNF docs need to be upgraded to reflect this, as of right now it points to google-services 4.0.1

**Comment by Subway19** [comment]
I was getting this error and I resolved this after a lot of efforts. Now I am stuck in this error.

`app.utils(...).checkPlayServicesAvailability is not a function`

Anybody can help me out on this?
